---
# Run with ansible-playbook <filename> -u root
#   (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- hosts: wordpress

  roles:
    - server
    - php
    - mysql
    - wordpress

  remote_user: admin
  become: yes
  become_user: root
  become_method: sudo
  vars:
    # used for filepaths
    site_name: "iksound"
    # used in the website's markup
    site_title: "iksound."
    # used in the web server configuration file
    site_url: "www.iksound.co.uk"


  tasks:
    - name: Create website directory
      file: path="/var/www/{{ site_name }}" state=directory mode=0755

    - name: create fast cgi cache directory
      file: path="/usr/share/nginx/cache/fcgi" state=directory mode=0755


    #
    # - name: Create nginx vhost config file
    #   template:
    #     src: "templates/website.conf"
    #     dest: "/etc/nginx/conf.d/{{ site_name }}.conf"
    #   notify:
    #   - restart nginx
    #   - enable nginx
    #
    # - name: Create website
    #   template:
    #     src: "templates/index.html"
    #     dest: "/var/www/{{ site_name }}/index.html"
    #
    # - name: Remove default nginx vhost configuration
    #   file: path=/etc/nginx/sites-enabled/default state=absent
    #   notify:
    #   - restart nginx
    #   - enable nginx

  # handlers:
  #   - name: restart nginx
  #     service:
  #       name: nginx
  #       state: restarted

    - name: enable nginx
      service:
        name: nginx
        enabled: yes
