---
# tasks file for server

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  upgrade: dist

- name: Install required software
  apt: name={{ item }} state=latest
  with_items:
    - nginx
    - mysql-server
    - python-mysqldb

- name: install PHP apps
  apt: name{{ item }} state=latest
  with_items:
    - php-mysql
    - php
    - php-mcrypt
    - php-fpm

- file:
   path: /var/www/html/index.html
   state: absent
